name = "Love Tropics 2026"
author = "The Love Tropics Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fac4f85eecea4f7b474b7cc8bf21a9fb398c3d772efc5abfb7fd45583345ae5"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.79"
