name = "Love Tropics 2025"
author = "The Love Tropics Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b53f921f5d81d7e52301413e13296bec4a0e7c6f6f6881eca0f7e05e7db5891"

[versions]
minecraft = "1.21.8"
neoforge = "21.8.47"
