[client]
# The URL of the minecraft server you wish to fetch mods from. This should be supplied by your server administrator
remoteServer = "https://ch3.lovetropics.org/"
# The server password: Change to the password you received from the server owner
password = "WeLoveTropics"
