name: Zip up Modpack

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          zip -r modpack.zip config/ icons/ mods/ packmenu/ servermods/ options.txt

      - uses: actions/upload-artifact@v2
        with:
          name: lt
          path: |
            modpack.zip
