name: Zip up Modpack

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3
        with:
          name: modpack
          path: |
            config/
            icons/
            mods/
            servermods/
            options.txt
